### ISSUE TITLE
sshd fails to launch.

### ISSUE THREAD

**Issue by rycuda** [strobi/docker-rpi-gitea#1]
sshd fails to launch, docker logs have a quantity of the following repeated as s6 tries repeatedly to launch sshd
```
/etc/ssh/sshd_config: line 22: Bad configuration option: CASignatureAlgorithms
/etc/ssh/sshd_config: terminating, 1 bad configuration options
```
Confirmed this by running sshd manually
```
# docker exec a8 sshd -T
/etc/ssh/sshd_config: line 22: Bad configuration option: CASignatureAlgorithms
/etc/ssh/sshd_config: terminating, 1 bad configuration options
```

Unsure if this is a specific compile option used for the sshd provided by alpine, or something elsewhere.
My current workaround is to simply `sed -i /CASignature/d /etc/templates/sshd_config` to remove the config line from the templates used to build the config file.

**Comment by strobh** [comment]
Thank you very much for your report!

I was finally able to take the time to look at it more closely. The problem was that OpenSSH has removed the `ssh-rsa` algorithm from the `CASignatureAlgorithms` option with version 8.2 (see [Release Notes of OpenSSH 8.2](https://www.openssh.com/txt/release-8.2)). I now manually remove only this algorithm from the sshd_config template file instead of removing the complete line, like you did.
